### ISSUE TITLE
Move filter function to another controller or directive controller

### ISSUE THREAD

**Issue by altescape** [GrantBartlett/full-stack-salary-survey#4]
Move this code https://github.com/GrantBartlett/full-stack-salary-survey/blob/1ab66f539913facf2095c544e528a26526a17c25/public/modules/salaries/controllers/salaries.client.controller.js#L90-L161

to another controller or directive and controller, that way controllers are nice and clean, tidy and small.
Call it salaries-filter.client.controller.js

**Comment by GrantBartlett** [comment]
https://github.com/GrantBartlett/full-stack-salary-survey/commit/64f2c4dc97e0aec2c7ac503a094608ffee0db983
